version: "3"
services:
  scylla-1:
    image: scylladb/scylla
    hostname: scylla-1
    command: --broadcast-address scylla-1 --listen-address scylla-1

  scylla-2:
    image: scylladb/scylla
    hostname: scylla-2
    command: --seeds scylla-1 --broadcast-address scylla-2 --listen-address scylla-2 --overprovisioned 1
    depends_on:
      - scylla-1

  scylla-3:
    image: scylladb/scylla
    hostname: scylla-3
    command: --seeds scylla-1 --broadcast-address scylla-3 --listen-address scylla-3 --overprovisioned 1
    depends_on:
      - scylla-1

